---
title: "event study specification"
author: "Devraj Kori"
date: "3/15/2020"
output: html_document
---
Event study possible specification
$$Y_{i,ht} = \sum_{\tau=-q}^m(\beta_{\tau}D^{\tau}_{i,h,t}) + \theta_{h} + \psi_t + \epsilon_{i,h,t}$$

+ $Y_{i,h,t}$ is equal to 1 if individual i in neighborhood h moves in time t.
+ $\tau$ is an event-time indicator which is equal to the difference between year t and the year that the apartment was constructed. 
+ $D^{\tau}_{i,h,t}$ is a set of event-time dummies equal to 1 if individual i in neighborhood h is within the treatment range around the location of the new apartment.
+ $\theta_h$ represents neighborhood fixed-effects
+ $\psi_t$ represents year fixed effects
+ $\epsilon_{i,h,t}$ is the error term, which should be uncorrelated with the other terms. 

* If there is a causal effect of the construction of a new apartment on displacement of nearby voucher residents, then the $\beta_{\tau}$ values will be close to zero for values of $\tau$ less than zero, and will be positive for values of $\tau$ greater than 0.
* Untreated observations for a given event serve as the control, most rows will be untreated

* The treatment range will be a ring around each new apartment location
* Rows are repeated for each event where an individual is treated. If individual i's location in year t is in the treatment range for two different events, the rows corresponding to i and t will be repeated for each event, with different taus assigned depending on when each apartment opened.
* Some rows will be eliminated if we can identify that individuals have been forcibly displaced prior to the construction of an apartment (i.e, if forced out by a landlord to make room for new construction)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


