---
title: "observe new apartments"
author: "Devraj Kori"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(sf)
library(leaflet)
library(ggmap)
library(rgdal)
library(tidycensus)
library(ggplot2)
library(dummies)
library(estimatr)
library(readxl)
```

```{r visualize_new_apartments,echo=FALSE}
setwd("..")

#set neighborhoods to include
included_neighborhoods<-c("East Liberty", "Homewood","Homewood West", "Homewood South","Homewood North",
                          "Larimer","Point Breeze","Point Breeze North", "East Hills", "Swisshelm Park",
                          "Shadyside", "Squirrel Hill North", "Squirrel Hill South", "Garfield", "Bloomfield",
                          "Highland Park", "Morningside",
                          "Greenfield", "Hazelwood","Glen Hazel", "Lincoln-Lemington-Belmar",
                          "Lower Lawrenceville", "Upper Lawrenceville", "Central Lawrenceville",
                          "Morningside", "Stanton Heights")

#read in new apartment complex data
market_rate<-read_csv("quantitative analysis/New Pgh Apartments - Large market-rate apts since 1999 - cleaned.csv")%>%
  #rename the units column
  mutate(units = `# mkt rate units`)%>%
  mutate(name=Notes)%>%
  select(lon,lat,units,name,Opened)%>%
  #remove NAS
  filter(!is.na(lon))%>%
  #add type label
  mutate(type="Market Rate")

mixed_income<-read_csv("quantitative analysis/New Mixed-Income Developments - Base List.csv")%>%
  # create units column
  mutate(units=`# mkt rate units`+`aff units?`)%>%
  mutate(name=`Notes / Building Name`)%>%
  select(lon,lat,units,name,Opened)%>%
  #remove NAS
  filter(!is.na(lon))%>%
  #add type label
  mutate(type="Mixed-income")
  
affordable<-read_csv("quantitative analysis/New Affordable Only Apts - Base List.csv")%>%
  mutate(units=`aff units?`)%>%
  mutate(name=Notes)%>%
  select(lon,lat,units,name,Opened)%>%
  #remove NAS
  filter(!is.na(lon))%>%
  #add type label
  mutate(type="Affordable Only")

apartments<-bind_rows(market_rate,mixed_income,affordable)%>%
  #make it sf object
  st_as_sf(coords=c("lon","lat"),crs = "+init=epsg:4326")
bnps<-bnps_recoded%>%
  mutate(type=paste(Type, "BNP"))
#load bnps
load("quantitative analysis/bnps re-geocoded.Rdata")
#read in neighborhoods
hoods<-neighborhoods<-read_sf("data preparation/geocode addresses/Neighborhoods_/Neighborhoods_.shx")%>%
  select(hood,geometry)%>%
  filter(hood%in%included_neighborhoods)
#defne palette
pal <- colorFactor(
  palette = "viridis",
  domain = c(apartments$type%>%unique(),
             bnps$type%>%unique()))

leaflet()%>%
  addProviderTiles(provider = "CartoDB.Positron", group = "Positron")%>%
  addCircleMarkers(data = apartments,
                   stroke = FALSE,
                   fillOpacity=.8,
                   radius=~units/15,
                   color = ~pal(type),
                   popup = ~paste(name,Opened))%>%
  #add BNPs to test overlap
  addCircleMarkers(data=bnps,
                   radius=8,
                   fillOpacity=.8,
                   stroke=FALSE,
                   color=~pal(type),
                   popup=~paste(`Development.Projects`,`Date-Completed`))%>%
  #add in neighborhood boundaries
  addPolylines(data=hoods,
               color="black",
               weight=3)%>%
  addLegend("bottomright", pal = pal, values = c(apartments$type%>%unique(),
                                                 bnps$type%>%unique()),
            title = "Apartment Type",
            opacity = 1)%>%
  #set the view to east liberty
  setView(lng=-79.9266587,lat=40.4656763,zoom=15)


```

```{r viz_razed_buildings}
setwd("..")

razed<-read_excel("quantitative analysis/razed.xlsx")%>%
  filter(Ward==11)


```